baseURL = 'https://example.org/'
title = 'Janek Piskorski'
theme = 'hugo-coder'
languageCode = "en"

[markup.highlight]
style = "github-dark"

[params]
author = "Janek Piskorski"
# user = "janek"
# hostname = "janekjan.github.io"
info = "Backend developer, music, audio and languages enthusiast"
keywords = "developer,personal,backend,music,audio.linguistics,blog"
description = "Janek's site"
since = 2023
avatarURL = "avatar.jpg"

# readingTime = false
# published = false
colorScheme = "dark"
hideColorSchemeToggle = true

[[params.social]]
key = 0
weight = 1
name = "Github"
url = "https://github.com/janekjan"
icon = "fa fa-github-square fa-2x"

[[params.social]]
key = 1
weight = 2
name = "LinkedIn"
url = "https://www.linkedin.com/in/jan-piskorski/"
icon = "fa fa-linkedin-square fa-2x"

[[params.social]]
key = 2
weight = 3
name = "Instagram"
url = "https://www.instagram.com/janekp00/"
icon = "fa fa-instagram fa-2x"

[[params.social]]
key = 3
weight = 4
name = "Mastodon"
url = "https://ieji.de/@janekjan_en"
icon = "fa fa-mastodon-square fa-2x"

[[menu.main]]
name = "projects"
weight = 1
url = "project-intro"

[[menu.main]]
name = "blog"
weight = 2
url = "blog/"


[menu]
	[[menu.header]]
	  name = "blog"
		weight = 1
		url = "blog"
  [[menu.header]]
    name = "projects"
		weight = 0
		url = "projects"